/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Characters */
        get: operations["list_characters_api_characters_get"];
        put?: never;
        /** Create Character */
        post: operations["create_character_api_characters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Character */
        get: operations["get_character_api_characters__cid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/actions/{action}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Attempts */
        get: operations["list_attempts_api_characters__cid__actions__action__attempts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/actions/{action}/attempts/{aid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attempt */
        get: operations["get_attempt_api_characters__cid__actions__action__attempts__aid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/actions/{action}/attempts/{aid}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Attempt */
        post: operations["accept_attempt_api_characters__cid__actions__action__attempts__aid__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/actions/{action}/attempts/{aid}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Attempt */
        post: operations["process_attempt_api_characters__cid__actions__action__attempts__aid__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/actions/{action}/attempts/{aid}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Attempt */
        post: operations["review_attempt_api_characters__cid__actions__action__attempts__aid__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/actions/{action}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Action */
        post: operations["generate_action_api_characters__cid__actions__action__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/actions/{action}/prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Prompt */
        post: operations["preview_prompt_api_characters__cid__actions__action__prompt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/actions/{action}/save-params": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Params */
        post: operations["save_params_api_characters__cid__actions__action__save_params_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/actions/{action}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Raw */
        post: operations["upload_raw_api_characters__cid__actions__action__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export */
        post: operations["export_api_characters__cid__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/export.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Zip */
        get: operations["export_zip_api_characters__cid__export_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/generate-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate All */
        post: operations["generate_all_api_characters__cid__generate_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Identity */
        get: operations["get_identity_api_characters__cid__identity_get"];
        /** Put Identity */
        put: operations["put_identity_api_characters__cid__identity_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/identity/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Identity */
        post: operations["analyze_identity_api_characters__cid__identity_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_characters__cid__plan_get"];
        /** Put Plan */
        put: operations["put_plan_api_characters__cid__plan_put"];
        /** Create Plan */
        post: operations["create_plan_api_characters__cid__plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Reference */
        post: operations["upload_reference_api_characters__cid__reference_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/reference/attempts/{aid}/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Reference */
        post: operations["select_reference_api_characters__cid__reference_attempts__aid__select_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{cid}/reference/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Reference */
        post: operations["generate_reference_api_characters__cid__reference_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{jid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__jid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{jid}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_jobs__jid__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Presets */
        get: operations["presets_api_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{cid}/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve */
        get: operations["serve_files__cid___path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptRequest */
        AcceptRequest: {
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** AcceptResult */
        AcceptResult: {
            /** Accepted */
            accepted: string;
            /** Derived */
            derived: string[];
            /** Forced */
            forced: boolean;
            /** Requalified Actions */
            requalified_actions: string[];
            /** Scale Profile Updated */
            scale_profile_updated: boolean;
            /** Unit */
            unit: string;
        };
        /** AttemptDetail */
        AttemptDetail: {
            /** Accepted */
            accepted: boolean;
            /** Attempt */
            attempt: string;
            files: components["schemas"]["AttemptFiles"];
            /** Generation */
            generation: {
                [key: string]: unknown;
            } | null;
            /** Process */
            process: {
                [key: string]: unknown;
            } | null;
            /** Qc */
            qc: {
                [key: string]: unknown;
            } | null;
            summary: components["schemas"]["AttemptSummary"];
            /** Unit */
            unit: string;
            /** Vision Review */
            vision_review?: {
                [key: string]: unknown;
            } | null;
        };
        /** AttemptFiles */
        AttemptFiles: {
            /** Clean */
            clean: string | null;
            /** Frames */
            frames: string[];
            /** Prompt */
            prompt: string | null;
            /** Raw */
            raw: string | null;
            /** Sheet */
            sheet: string | null;
        };
        /** AttemptList */
        AttemptList: {
            /** Accepted Attempt */
            accepted_attempt: string | null;
            /** Action */
            action: string;
            /** Attempts */
            attempts: components["schemas"]["AttemptSummary"][];
            /** Direction */
            direction: string | null;
            /** Mirror Of */
            mirror_of: string | null;
            /** Unit */
            unit: string;
        };
        /** AttemptResult */
        AttemptResult: {
            /** Attempt */
            attempt: string;
            /** Derived */
            derived: {
                [key: string]: unknown;
            };
            files: components["schemas"]["AttemptFiles"];
            qc: components["schemas"]["Qc"];
            /** Unit */
            unit: string;
        };
        /** AttemptSummary */
        AttemptSummary: {
            /** Accepted */
            accepted: boolean;
            /** Attempt */
            attempt: string;
            /** Created At */
            created_at?: string | null;
            /** Extra */
            extra?: string | null;
            /** Generation Status */
            generation_status?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Provider */
            provider?: string | null;
            /** Qc Status */
            qc_status?: string | null;
            /**
             * Recovery
             * @default []
             */
            recovery: string[];
            /** Score */
            score?: number | null;
            /** Sheet */
            sheet: string | null;
        };
        /** Body_upload_raw_api_characters__cid__actions__action__upload_post */
        Body_upload_raw_api_characters__cid__actions__action__upload_post: {
            /** File */
            file: string;
        };
        /** Body_upload_reference_api_characters__cid__reference_post */
        Body_upload_reference_api_characters__cid__reference_post: {
            /** File */
            file: string;
        };
        /** CharacterCreate */
        CharacterCreate: {
            /**
             * Art Style
             * @default auto
             * @enum {string}
             */
            art_style: "auto" | "pixel_art" | "retro_pixel" | "pixel_inspired" | "clean_hd" | "project_native";
            /**
             * Asset Type
             * @default character
             * @enum {string}
             */
            asset_type: "player" | "npc" | "character" | "creature" | "enemy";
            /** Id */
            id: string;
            /**
             * View
             * @default side
             * @enum {string}
             */
            view: "side" | "topdown" | "3/4" | "front" | "rear";
        };
        /** ExportResponse */
        ExportResponse: {
            /** Files */
            files: string[];
            /** Warnings */
            warnings: string[];
        };
        /** GenerateAllRequest */
        GenerateAllRequest: {
            /** Actions */
            actions?: string[] | null;
            /**
             * Auto Accept
             * @default true
             */
            auto_accept: boolean;
            /**
             * Max Regenerations
             * @default 1
             */
            max_regenerations: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IdentityAnalyzeRequest */
        IdentityAnalyzeRequest: {
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** IdentityResponse */
        IdentityResponse: {
            /** Profile */
            profile: {
                [key: string]: unknown;
            } | null;
        };
        /** IdentityUpdate */
        IdentityUpdate: {
            /** Identity */
            identity: {
                [key: string]: unknown;
            };
        };
        /** Job */
        Job: {
            /** Action */
            action?: string | null;
            /** Attempt */
            attempt?: string | null;
            /** Character */
            character: string;
            /** Created At */
            created_at: string;
            /** Direction */
            direction?: string | null;
            /**
             * Elapsed S
             * @default 0
             */
            elapsed_s: number;
            error?: components["schemas"]["JobError"] | null;
            /** Expected S */
            expected_s?: number | null;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            /**
             * Log
             * @default []
             */
            log: components["schemas"]["LogLine"][];
            progress?: components["schemas"]["Progress"] | null;
            /**
             * Queue Position
             * @default 0
             */
            queue_position: number;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Stage */
            stage?: string | null;
            /** Started At */
            started_at?: string | null;
            /**
             * State
             * @default queued
             * @enum {string}
             */
            state: "queued" | "running" | "succeeded" | "failed" | "canceled" | "interrupted";
            /**
             * Type
             * @enum {string}
             */
            type: "reference_generate" | "identity_analyze" | "action_generate" | "batch_generate" | "vision_review";
        };
        /** JobCreated */
        JobCreated: {
            /** Attempt */
            attempt?: string | null;
            job: components["schemas"]["Job"];
        };
        /** JobError */
        JobError: {
            /** Code */
            code: string;
            /**
             * Detail
             * @default {}
             */
            detail: {
                [key: string]: unknown;
            };
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** JobList */
        JobList: {
            /** Jobs */
            jobs: components["schemas"]["Job"][];
        };
        /** JobResponse */
        JobResponse: {
            job: components["schemas"]["Job"];
        };
        /** LogLine */
        LogLine: {
            /** Level */
            level: string;
            /** T */
            t: string;
            /** Text */
            text: string;
        };
        /** PlanCreate */
        PlanCreate: {
            /** Actions */
            actions?: string[] | null;
            /** Bundle */
            bundle?: string | null;
            /**
             * Cell
             * @default 128x128
             */
            cell: string;
            /** Directions */
            directions?: ("down" | "up" | "right" | "left")[] | null;
            /** Facing */
            facing?: string | null;
            /** Mirror */
            mirror?: boolean | null;
            /**
             * Set
             * @default []
             */
            set: string[];
            /** View */
            view?: ("side" | "topdown" | "3/4" | "front" | "rear") | null;
        };
        /** PlanResponse */
        PlanResponse: {
            /** Estimated Seconds */
            estimated_seconds: number;
            /** Plan */
            plan: {
                [key: string]: unknown;
            };
            /** Units */
            units: components["schemas"]["UnitInfo"][];
        };
        /** PlanUpdate */
        PlanUpdate: {
            /** Plan */
            plan: {
                [key: string]: unknown;
            };
        };
        /** ProcessRequest */
        ProcessRequest: {
            /**
             * Set
             * @default {}
             */
            set: {
                [key: string]: string | number | boolean;
            };
        };
        /** Progress */
        Progress: {
            /** Current */
            current?: string | null;
            /** Done */
            done: number;
            /** Total */
            total: number;
        };
        /** PromptRequest */
        PromptRequest: {
            /** Extra */
            extra?: string | null;
            /**
             * Recovery
             * @default []
             */
            recovery: string[];
        };
        /** PromptResponse */
        PromptResponse: {
            /** Prompt */
            prompt: string;
            /** References Needed */
            references_needed: string[];
            /** Warnings */
            warnings: string[];
        };
        /** Qc */
        Qc: {
            /** Recommendations */
            recommendations: {
                [key: string]: unknown;
            }[];
            /** Results */
            results: {
                [key: string]: unknown;
            }[];
            /** Score */
            score: number;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** ReferenceFiles */
        ReferenceFiles: {
            /** Character */
            character: string | null;
            /** Keyed */
            keyed: string | null;
            /** Source */
            source: string | null;
        };
        /** ReferenceGenerateRequest */
        ReferenceGenerateRequest: {
            /**
             * Count
             * @default 1
             */
            count: number;
            /** Description */
            description: string;
        };
        /** ReferenceResponse */
        ReferenceResponse: {
            /** Bg Removed */
            bg_removed: boolean;
            files: components["schemas"]["ReferenceFiles"];
            /** Reference */
            reference: string;
            /** Selected Attempt */
            selected_attempt?: string | null;
        };
        /** SaveParamsRequest */
        SaveParamsRequest: {
            /** Set */
            set: {
                [key: string]: string;
            };
        };
        /** SaveParamsResult */
        SaveParamsResult: {
            /** Action */
            action: string;
            /** Saved */
            saved: {
                [key: string]: string;
            };
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
        };
        /** UnitInfo */
        UnitInfo: {
            /** Action */
            action: string;
            /** Direction */
            direction: string;
            /** Mirrored */
            mirrored: boolean;
            /** Unit */
            unit: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_characters_api_characters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    create_character_api_characters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_character_api_characters__cid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_attempts_api_characters__cid__actions__action__attempts_get: {
        parameters: {
            query?: {
                /** @description down|up|right|left; required when the plan has 2+ directions */
                direction?: ("down" | "up" | "right" | "left") | null;
            };
            header?: never;
            path: {
                cid: string;
                action: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attempt_api_characters__cid__actions__action__attempts__aid__get: {
        parameters: {
            query?: {
                /** @description down|up|right|left; required when the plan has 2+ directions */
                direction?: ("down" | "up" | "right" | "left") | null;
            };
            header?: never;
            path: {
                cid: string;
                action: string;
                aid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_attempt_api_characters__cid__actions__action__attempts__aid__accept_post: {
        parameters: {
            query?: {
                /** @description down|up|right|left; required when the plan has 2+ directions */
                direction?: ("down" | "up" | "right" | "left") | null;
            };
            header?: never;
            path: {
                cid: string;
                action: string;
                aid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AcceptRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_attempt_api_characters__cid__actions__action__attempts__aid__process_post: {
        parameters: {
            query?: {
                /** @description down|up|right|left; required when the plan has 2+ directions */
                direction?: ("down" | "up" | "right" | "left") | null;
            };
            header?: never;
            path: {
                cid: string;
                action: string;
                aid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProcessRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_attempt_api_characters__cid__actions__action__attempts__aid__review_post: {
        parameters: {
            query?: {
                /** @description down|up|right|left; required when the plan has 2+ directions */
                direction?: ("down" | "up" | "right" | "left") | null;
            };
            header?: never;
            path: {
                cid: string;
                action: string;
                aid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_action_api_characters__cid__actions__action__generate_post: {
        parameters: {
            query?: {
                /** @description down|up|right|left; required when the plan has 2+ directions */
                direction?: ("down" | "up" | "right" | "left") | null;
            };
            header?: never;
            path: {
                cid: string;
                action: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PromptRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_prompt_api_characters__cid__actions__action__prompt_post: {
        parameters: {
            query?: {
                /** @description down|up|right|left; required when the plan has 2+ directions */
                direction?: ("down" | "up" | "right" | "left") | null;
            };
            header?: never;
            path: {
                cid: string;
                action: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PromptRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_params_api_characters__cid__actions__action__save_params_post: {
        parameters: {
            query?: {
                /** @description down|up|right|left; required when the plan has 2+ directions */
                direction?: ("down" | "up" | "right" | "left") | null;
            };
            header?: never;
            path: {
                cid: string;
                action: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveParamsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveParamsResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_raw_api_characters__cid__actions__action__upload_post: {
        parameters: {
            query?: {
                /** @description down|up|right|left; required when the plan has 2+ directions */
                direction?: ("down" | "up" | "right" | "left") | null;
            };
            header?: never;
            path: {
                cid: string;
                action: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_raw_api_characters__cid__actions__action__upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_characters__cid__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_zip_api_characters__cid__export_zip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_all_api_characters__cid__generate_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GenerateAllRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_identity_api_characters__cid__identity_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_identity_api_characters__cid__identity_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_identity_api_characters__cid__identity_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IdentityAnalyzeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_characters__cid__plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_plan_api_characters__cid__plan_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_api_characters__cid__plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_reference_api_characters__cid__reference_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_reference_api_characters__cid__reference_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_reference_api_characters__cid__reference_attempts__aid__select_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
                aid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_reference_api_characters__cid__reference_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferenceGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: {
                refresh?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                active?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__jid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__jid__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presets_api_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    serve_files__cid___path__get: {
        parameters: {
            query?: {
                v?: string | null;
            };
            header?: never;
            path: {
                cid: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
